/**
 * CATÁLOGO OFICIAL OPEN-SOURCE DE VIDEOJUEGOS - EZZE.GAMES
 * 16 Videojuegos completos, terminados, 100% autohospedados y sin anuncios.
 */

const CATEGORIES = [
  { id: 'todos', name: 'Todos', icon: '🎮' },
  { id: 'arcade', name: 'Arcade & Clásicos', icon: '👾' },
  { id: 'puzzles', name: 'Puzzles & Mente', icon: '🧩' },
  { id: 'carreras', name: 'Carreras & 3D', icon: '🏎️' },
  { id: 'estrategia', name: 'Estrategia & Mesa', icon: '♟️' },
  { id: 'favoritos', name: 'Mis Favoritos', icon: '💖' }
];

const LOCAL_GAMES = [
  // --- ARCADE & CLÁSICOS ---
  {
    id: 'pacman-hd',
    slug: 'pacman-hd',
    title: 'Pac-Man Arcade HD',
    category: 'arcade',
    tags: ['Arcade', 'Retro', 'Pacman', 'Fantasmas'],
    description: 'La leyenda de las maquinitas recreativas. Come todos los puntos del laberinto y esquiva a los 4 fantasmas.',
    rating: 4.9,
    plays: 18500,
    featured: true,
    trending: true,
    badge: 'LEGENDARIO 🌟',
    coverImage: '/assets/covers/pacman-hd.jpg',
    accentColor: '#facc15',
    bannerGradient: 'linear-gradient(135deg, #facc15, #ca8a04)',
    gamePath: '/games/pacman-hd/index.html'
  },
  {
    id: 'clumsy-bird',
    slug: 'clumsy-bird',
    title: 'Clumsy Bird HD',
    category: 'arcade',
    tags: ['Flappy', 'Volar', 'Habilidad', 'Casual'],
    description: 'El clásico juego de aletear por los cielos esquivando tuberías. ¿Cuál será tu puntuación récord?',
    rating: 4.8,
    plays: 14200,
    featured: true,
    trending: true,
    badge: 'HOT 🔥',
    coverImage: '/assets/covers/clumsy-bird.svg',
    accentColor: '#38bdf8',
    bannerGradient: 'linear-gradient(135deg, #38bdf8, #0284c7)',
    gamePath: '/games/clumsy-bird/index.html'
  },
  {
    id: 'alien-invasion',
    slug: 'alien-invasion',
    title: 'Alien Invasion Space Shooter',
    category: 'arcade',
    tags: ['Espacio', 'Naves', 'Retro', 'Disparos'],
    description: 'Defiende la galaxia de oleadas de invasores alienígenas en este clásico shooter retro con sonidos y armas láser.',
    rating: 4.7,
    plays: 9600,
    featured: false,
    trending: true,
    badge: 'ARCADE 👾',
    coverImage: '/assets/covers/alien-invasion.svg',
    accentColor: '#ec4899',
    bannerGradient: 'linear-gradient(135deg, #ec4899, #be185d)',
    gamePath: '/games/alien-invasion/index.html'
  },
  {
    id: 'tetris-pro',
    slug: 'tetris-pro',
    title: 'Retro Tetris Pro',
    category: 'arcade',
    tags: ['Tetris', 'Bloques', 'Lógica', 'Clásico'],
    description: 'Acomoda las piezas geométricas, completa líneas horizontales y alcanza la máxima puntuación en este clásico inmortal.',
    rating: 4.9,
    plays: 21000,
    featured: true,
    trending: true,
    badge: 'TOP 🏆',
    coverImage: '/assets/covers/tetris-pro.svg',
    accentColor: '#3b82f6',
    bannerGradient: 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
    gamePath: '/games/tetris-pro/index.html'
  },
  {
    id: 'snake-classic',
    slug: 'snake-classic',
    title: 'Snake Classic HD',
    category: 'arcade',
    tags: ['Serpiente', 'Retro', 'Nostalgia', 'Arcade'],
    description: 'El legendario juego de la serpiente. Come manzanas, crece sin chocar contra las paredes ni tu propia cola.',
    rating: 4.8,
    plays: 11300,
    featured: false,
    trending: false,
    badge: 'CLÁSICO 🐍',
    coverImage: '/assets/covers/snake-classic.svg',
    accentColor: '#22c55e',
    bannerGradient: 'linear-gradient(135deg, #22c55e, #15803d)',
    gamePath: '/games/snake-classic/index.html'
  },
  {
    id: 'astray-3d',
    slug: 'astray-3d',
    title: 'Astray 3D Maze Escape',
    category: 'carreras',
    tags: ['3D', 'Laberinto', 'Física', 'Aventura'],
    description: 'Guía la esfera brillante a través de laberintos en 3D con físicas reales, iluminación dinámica y contrarreloj.',
    rating: 4.8,
    plays: 8700,
    featured: false,
    trending: true,
    badge: '3D 🕶️',
    coverImage: '/assets/covers/astray-3d.svg',
    accentColor: '#38bdf8',
    bannerGradient: 'linear-gradient(135deg, #38bdf8, #0369a1)',
    gamePath: '/games/astray-3d/index.html'
  },

  // --- PUZZLES & MENTE ---
  {
    id: 'puzzle-2048',
    slug: 'puzzle-2048',
    title: '2048 Original Master',
    category: 'puzzles',
    tags: ['Números', 'Lógica', 'Mente', 'Adictivo'],
    description: 'Desliza las fichas numéricas, combina múltiplos idénticos y alcanza la mítica ficha 2048.',
    rating: 4.9,
    plays: 24500,
    featured: true,
    trending: true,
    badge: 'POPULAR ⭐',
    coverImage: '/assets/covers/puzzle-2048.svg',
    accentColor: '#facc15',
    bannerGradient: 'linear-gradient(135deg, #facc15, #b45309)',
    gamePath: '/games/puzzle-2048/index.html'
  },
  {
    id: 'hextris-hd',
    slug: 'hextris-hd',
    title: 'Hextris Hexagonal HD',
    category: 'puzzles',
    tags: ['Hexágono', 'Colores', 'Combos', 'Frenético'],
    description: 'Gira el hexágono central para agrupar 3 bloques del mismo color antes de que la torre llegue al borde exterior.',
    rating: 4.8,
    plays: 13800,
    featured: false,
    trending: true,
    badge: 'HEX 🔷',
    coverImage: '/assets/covers/hextris-hd.svg',
    accentColor: '#06b6d4',
    bannerGradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
    gamePath: '/games/hextris-hd/index.html'
  },
  {
    id: 'tower-master',
    slug: 'tower-master',
    title: 'Tower Master 3D',
    category: 'puzzles',
    tags: ['Construcción', 'Física', 'Torre', 'Habilidad'],
    description: '¡Toca en el momento exacto para soltar los pisos y construir el rascacielos más alto del mundo!',
    rating: 4.7,
    plays: 12100,
    featured: false,
    trending: true,
    badge: 'TORRE 🏗️',
    coverImage: '/assets/covers/tower-master.svg',
    accentColor: '#f97316',
    bannerGradient: 'linear-gradient(135deg, #f97316, #c2410c)',
    gamePath: '/games/tower-master/index.html'
  },
  {
    id: 'sandboxels',
    slug: 'sandboxels',
    title: 'Sandboxels Simulator',
    category: 'puzzles',
    tags: ['Simulador', 'Física', 'Arena', 'Creatividad'],
    description: 'Simulador de física y química en tiempo real. Experimenta con arena, agua, fuego, lava, plantas y explosivos.',
    rating: 4.9,
    plays: 19800,
    featured: true,
    trending: true,
    badge: 'CIENCIA 🔬',
    coverImage: '/assets/covers/sandboxels.svg',
    accentColor: '#facc15',
    bannerGradient: 'linear-gradient(135deg, #facc15, #a16207)',
    gamePath: '/games/sandboxels/index.html'
  },
  {
    id: 'solitaire-classic',
    slug: 'solitaire-classic',
    title: 'Solitario Klondike Clásico',
    category: 'puzzles',
    tags: ['Cartas', 'Solitario', 'Mesa', 'Ingenio'],
    description: 'El clásico juego de cartas de paciencia. Ordena las 4 familias por palos del As al Rey.',
    rating: 4.8,
    plays: 16500,
    featured: false,
    trending: false,
    badge: 'CARTAS 🃏',
    coverImage: '/assets/covers/solitaire-classic.svg',
    accentColor: '#16a34a',
    bannerGradient: 'linear-gradient(135deg, #16a34a, #14532d)',
    gamePath: '/games/solitaire-classic/index.html'
  },
  {
    id: 'minesweeper',
    slug: 'minesweeper',
    title: 'Buscaminas Retro Master',
    category: 'puzzles',
    tags: ['Lógica', 'Buscaminas', 'Retro', 'Mente'],
    description: 'Despeja el campo minado utilizando las pistas numéricas sin pisar ninguna bomba oculta.',
    rating: 4.7,
    plays: 8900,
    featured: false,
    trending: false,
    badge: 'LÓGICA 💣',
    coverImage: '/assets/covers/minesweeper.svg',
    accentColor: '#ef4444',
    bannerGradient: 'linear-gradient(135deg, #ef4444, #991b1b)',
    gamePath: '/games/minesweeper/index.html'
  },

  // --- CARRERAS, DEPORTES & MESA ---
  {
    id: 'hexgl-racing',
    slug: 'hexgl-racing',
    title: 'HexGL 3D Futuristic Racing',
    category: 'carreras',
    tags: ['3D', 'Sci-Fi', 'Carreras', 'Velocidad'],
    description: 'Compite a velocidades hiperbólicas en pistas futuristas flotantes en 3D con propulsores turbo.',
    rating: 4.9,
    plays: 22400,
    featured: true,
    trending: true,
    badge: 'VELOCIDAD ⚡',
    coverImage: '/assets/covers/hexgl-racing.svg',
    accentColor: '#06b6d4',
    bannerGradient: 'linear-gradient(135deg, #06b6d4, #0e7490)',
    gamePath: '/games/hexgl-racing/index.html'
  },
  {
    id: 'canvas-rider',
    slug: 'canvas-rider',
    title: 'Canvas Rider: Bike Stunts',
    category: 'carreras',
    tags: ['Bicicleta', 'Acrobacias', 'Física', 'Rider'],
    description: 'Conduce y realiza piruetas acrobáticas en pistas de física dibujadas a mano superando grandes colinas y valles.',
    rating: 4.8,
    plays: 15300,
    featured: false,
    trending: true,
    badge: 'BIKE 🚴',
    coverImage: '/assets/covers/canvas-rider.svg',
    accentColor: '#38bdf8',
    bannerGradient: 'linear-gradient(135deg, #38bdf8, #0369a1)',
    gamePath: '/games/canvas-rider/index.html'
  },
  {
    id: 'chess-master',
    slug: 'chess-master',
    title: 'Chess Grandmaster Pro',
    category: 'estrategia',
    tags: ['Ajedrez', 'Estrategia', 'Mente', 'IA'],
    description: 'El juego de reyes definitivo. Juega partidas de ajedrez contra la inteligencia artificial o contra un amigo.',
    rating: 4.9,
    plays: 14700,
    featured: false,
    trending: true,
    badge: 'AJEDREZ ♟️',
    coverImage: '/assets/covers/chess-master.svg',
    accentColor: '#f59e0b',
    bannerGradient: 'linear-gradient(135deg, #f59e0b, #78350f)',
    gamePath: '/games/chess-master/index.html'
  },
  {
    id: 'connect-four',
    slug: 'connect-four',
    title: '4 en Línea (Connect Four)',
    category: 'estrategia',
    tags: ['Mesa', 'Conectar', 'Estrategia', 'Multijugador'],
    description: 'Conecta 4 fichas de tu color en línea vertical, horizontal o diagonal antes que tu rival.',
    rating: 4.8,
    plays: 12600,
    featured: false,
    trending: false,
    badge: 'ESTRATEGIA 🔴',
    coverImage: '/assets/covers/connect-four.svg',
    accentColor: '#3b82f6',
    bannerGradient: 'linear-gradient(135deg, #3b82f6, #1e3a8a)',
    gamePath: '/games/connect-four/index.html'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LOCAL_GAMES;
}
