/**
 * CATÁLOGO INICIAL Y METADATOS DE JUEGOS PARA "eze"
 */

const LOCAL_GAMES = [
  {
    id: 'vaso-feliz',
    slug: 'vaso-feliz',
    title: 'Vaso Feliz: Física',
    category: 'puzzles',
    tags: ['Física', 'Dibujo', 'Agua', 'Ingenio'],
    description: '¡Dibuja rampas con tinta mágica para guiar el torrente de agua y hacer sonreír al vaso triste!',
    rating: 4.9,
    plays: 2400,
    featured: true,
    trending: true,
    badge: 'POPULAR 🌟',
    thumbnail: '🥛',
    accentColor: '#38bdf8',
    bannerGradient: 'linear-gradient(135deg, #0284c7, #0369a1)',
    gamePath: 'games/vaso-feliz/index.html'
  },
  {
    id: 'cerebro-loco',
    slug: 'cerebro-loco',
    title: 'Cerebro Loco: Acertijos',
    category: 'puzzles',
    tags: ['Puzzles', 'Acertijos', 'Ingenio', 'Lógica'],
    description: '¡Pon a prueba tu mente con acertijos tramposos! Arrastra objetos, descubre secretos y piensa fuera de la caja.',
    rating: 4.9,
    plays: 1850,
    featured: true,
    trending: true,
    badge: 'MENTE 🧠',
    thumbnail: '💡',
    accentColor: '#f59e0b',
    bannerGradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    gamePath: 'games/cerebro-loco/index.html'
  },
  {
    id: 'nivel-maldito',
    slug: 'nivel-maldito',
    title: 'Nivel Maldito',
    category: 'arcade',
    tags: ['Troll', 'Plataformas', 'Desafío', 'Divertido'],
    description: '¡El juego de plataformas más troll y adictivo! Esquiva suelos falsos, puertas que huyen y techos aplastantes.',
    rating: 4.9,
    plays: 2150,
    featured: true,
    trending: true,
    badge: 'TENDENCIA 🔥',
    thumbnail: '😈',
    accentColor: '#ef4444',
    bannerGradient: 'linear-gradient(135deg, #ef4444, #991b1b)',
    gamePath: 'games/nivel-maldito/index.html'
  },
  {
    id: 'angry-pigs-3d',
    slug: 'angry-pigs-3d',
    title: 'Angry Pigs 3D',
    category: '3d',
    tags: ['3D', 'Física', 'Acción', 'Destrucción'],
    description: '¡Lanza cerdos en un valle 3D masivo con cámara lenta y destruye las fortalezas de los pájaros!',
    rating: 4.9,
    plays: 1420,
    featured: true,
    trending: true,
    badge: 'HOT 🔥',
    thumbnail: '🐷',
    accentColor: '#2ecc71',
    bannerGradient: 'linear-gradient(135deg, #10b981, #047857)',
    gamePath: 'games/angry-pigs-3d/index.html'
  },
  {
    id: 'retro-knight',
    slug: 'retro-knight',
    title: 'Leyenda del Reino Dorado',
    category: 'aventura',
    tags: ['Aventura', 'Retro', 'Pixel Art', 'RPG'],
    description: 'Explora el bosque, la cueva de los murciélagos y el castillo real para conseguir el cofre legendario.',
    rating: 4.8,
    plays: 980,
    featured: true,
    trending: false,
    badge: 'NUEVO ⭐',
    thumbnail: '⚔️',
    accentColor: '#f1c40f',
    bannerGradient: 'linear-gradient(135deg, #f59e0b, #b45309)',
    gamePath: 'games/retro-knight/index.html'
  },
  {
    id: 'cyber-runner',
    slug: 'cyber-runner',
    title: 'Cyber Runner 2099',
    category: 'carreras',
    tags: ['Carreras', 'Cyberpunk', 'Velocidad', 'Arcade'],
    description: 'Esquiva láseres y obstáculos a toda velocidad en una pista futurista de neón.',
    rating: 4.7,
    plays: 1250,
    featured: true,
    trending: true,
    badge: 'TOP 🏆',
    thumbnail: '🏎️',
    accentColor: '#00d2d3',
    bannerGradient: 'linear-gradient(135deg, #06b6d4, #0e7490)',
    gamePath: 'games/cyber-runner/index.html'
  },
  {
    id: 'puzzle-2048',
    slug: 'puzzle-2048',
    title: 'Neon 2048 Master',
    category: 'puzzles',
    tags: ['Puzzles', 'Estrategia', 'Lógica', 'Mente'],
    description: 'Combina los bloques numéricos brillantes hasta alcanzar la legendaria ficha 2048.',
    rating: 4.6,
    plays: 830,
    featured: false,
    trending: false,
    badge: 'LÓGICA 🧠',
    thumbnail: '🧩',
    accentColor: '#ff9f43',
    bannerGradient: 'linear-gradient(135deg, #f97316, #c2410c)',
    gamePath: 'games/puzzle-2048/index.html'
  },
  {
    id: 'space-arcade',
    slug: 'space-arcade',
    title: 'Space Defenders Retro',
    category: 'arcade',
    tags: ['Arcade', 'Espacio', 'Disparos', 'Clásico'],
    description: 'Defiende la galaxia contra oleadas de invasores extraterrestres en este shooter clásico.',
    rating: 4.5,
    plays: 720,
    featured: false,
    trending: false,
    badge: 'CLÁSICO 👾',
    thumbnail: '🚀',
    accentColor: '#54a0ff',
    bannerGradient: 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
    gamePath: 'games/space-arcade/index.html'
  }
];

const CATEGORIES = [
  { id: 'todos', name: 'Todos', icon: '🎮' },
  { id: '3d', name: 'Juegos 3D', icon: '🕶️' },
  { id: 'aventura', name: 'Aventura', icon: '🌲' },
  { id: 'carreras', name: 'Carreras', icon: '🏎️' },
  { id: 'puzzles', name: 'Puzzles', icon: '🧩' },
  { id: 'arcade', name: 'Arcade', icon: '👾' },
  { id: 'favoritos', name: 'Mis Favoritos', icon: '⭐' }
];
